# Fzf
export FZF_DEFAULT_OPTS=" \
  --color=bg+:#363A4F,bg:#24273A,spinner:#F4DBD6,hl:#ED8796 \
  --color=fg:#CAD3F5,header:#ED8796,info:#B7BDF8,pointer:#B7BDF8 \
  --color=marker:#B7BDF8,fg+:#B7BDF8,prompt:#B7BDF8,hl+:#ED8796 \
  --color=selected-bg:#494D64 \
  --color=border:#B7BDF8,label:#CAD3F5 \
  --style=full \
  --preview '[ -d {} ] && eza --icons=auto --tree --level=2 --color=always {} || bat --style=numbers --color=always --line-range :500 {}'
  --bind 'ctrl-c:execute-silent(realpath {} | wl-copy)' \
  --bind 'ctrl-e:execute(nvim {})' \
"

export FZF_CTRL_R_OPTS="$FZF_DEFAULT_OPTS"

export FZF_DEFAULT_COMMAND="fd -H -L -E '.git' -E '.npm*' -E '.nix*'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export FZF_ALT_C_COMMAND="fd -t d -H -L -E '.git'"
export FZF_ALT_C_OPTS="$FZF_DEFAULT_OPTS"

source <(fzf --zsh)

# Eza
alias eza="eza --icons=auto -l --modified --time-style='+%d %B %H:%M' --no-permissions --group-directories-first --header"
alias ls="eza"

# Zoxide
alias cd="z"

# Bat
alias cat="bat"

# Duf 
alias df="duf"

# Dust
alias du="dust"

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
  print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
  command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
  command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
    print -P "%F{33} %F{34}Installation successful.%f%b" || \
    print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Plugins
zinit ice wait"0" lucid
zinit light zsh-users/zsh-completions
zinit ice atload"_zsh_autosuggest_start"
zinit light zsh-users/zsh-autosuggestions
zinit ice wait"0" lucid
zinit light zdharma-continuum/fast-syntax-highlighting
zinit ice wait"0" lucid
zinit light Aloxaf/fzf-tab
zstyle ":fzf-tab:*" fzf-flags --border --color=bg+:#363A4F,bg:#24273A,spinner:#F4DBD6,hl:#ED8796,fg:#CAD3F5,header:#ED8796,info:#B7BDF8,pointer:#B7BDF8,marker:#B7BDF8,fg+:#B7BDF8,prompt:#B7BDF8,hl+:#ED8796,selected-bg:#494D64,border:#B7BDF8,label:#CAD3F5
zstyle ":fzf-tab:complete:cd:*" fzf-preview "eza -1 --color=always $realpath"
zstyle ":fzf-tab:complete:systemctl-*:*" fzf-preview "SYSTEMD_COLORS=1 systemctl status $word"

# Theme
source ~/.theme.zsh-theme

# Fastfetch
fastfetch

# Correction
setopt CORRECT

# Default editor
export EDITOR=nvim
