general {
  no_fade_in = false
  grace = 0
  disable_loading = true
}

background {
  monitor =
  path = screenshot
  color =
  blur_passes = 2 
  blur_size = 7
}

input-field {
  monitor =
  size = 250, 60
  outline_thickness = 4
  fade_on_empty = false
  inner_color = rgb(36, 39, 58)
  outer_color = rgb(183, 189, 248)
  check_color = rgb(245, 189, 230)
  fail_color = rgb(237, 135, 150)
  font_color = rgb(202, 211, 245) 
  dots_center = true
  position = 0, -250
  halign = center
  valign = center
}

label {
  monitor =
  text = $TIME
  color = rgb(202, 211, 245)
  font_size = 150
  font_family = FiraCode Nerd Font
  position = 0, 200
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +'%A, %e %B')"
  color = rgb(202, 211, 245)
  font_size = 28
  font_family = FiraCode Nerd Font
  position = 0, 70
  halign = center
  valign = center
}

image {
  monitor =
  path = /home/bopsifox/.config/niri/avatar.jpg
  size = 150
  rounding = -1
  rotate = 0
  border_size = 0
  reload_time = -1
  position = 0, -50
  halign = center
  valign = center
}

label {
  monitor =
  text = Hello, $USER
  color = rgb(202, 211, 245)
  font_size = 25
  font_family = FiraCode Nerd Font
  position = 0, -170
  halign = center
  valign = center
}
