Window.SetBackgroundTopColor (0.141, 0.152, 0.227);
Window.SetBackgroundBottomColor (0.141, 0.152, 0.227);

logo_image = Image("logo.png");

logo_sprite = Sprite();
logo_sprite.SetImage(logo_image);

screen_width = Window.GetWidth();
screen_height = Window.GetHeight();
logo_width = logo_image.GetWidth();
logo_height = logo_image.GetHeight();

logo_sprite.SetX (screen_width / 2 - logo_width / 2);
logo_sprite.SetY (screen_height / 2 - logo_height / 2);
