# Fzf
export FZF_DEFAULT_OPTS=" \
  --color=bg+:#363A4F,bg:#24273A,spinner:#F4DBD6,hl:#ED8796 \
  --color=fg:#CAD3F5,header:#ED8796,info:#B7BDF8,pointer:#B7BDF8 \
  --color=marker:#B7BDF8,fg+:#B7BDF8,prompt:#B7BDF8,hl+:#ED8796 \
  --color=selected-bg:#494D64 \
  --color=border:#B7BDF8,label:#CAD3F5 \
  --style=full \
  --preview '[ -d {} ] && eza --tree --level=2 --color=always {} || bat --style=numbers --color=always --line-range :500 {} || ~/.fzf-preview.sh {}'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | wl-copy)+abort' \
  --bind 'ctrl-e:execute(nvim {})+abort' \
  --bind 'ctrl-u:preview-page-up' \
  --bind 'ctrl-d:preview-page-down' \
"

export FZF_CTRL_R_OPTS=" \
  --preview 'echo {}' --preview-window down:3:hidden:wrap \
  --bind 'ctrl-/:toggle-preview' \
  --color=header:#ED8796 --header 'Press CTRL-/ to toggle full command view' \
"

export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --exclude /nix/store/ --exclude /nix/profiles/'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"

fn() {
  local file
  file=$(fd --type f --hidden --exclude .git | fzf --query="$1" --select-1 --exit-0)
  [ -n "$file" ] && nvim "$file"
}

# Eza
alias eza='LC_TIME=C eza --icons=auto -l --modified --time-style="+%d %B %H:%M" --no-permissions --group-directories-first --header'
alias ls='eza'

# Zoxide
alias cd='z'

# NixOS alias
alias rebuild='nh os switch' # Analogue nixos-rebuild switch
alias nos='nh os switch'
alias ns='nh search' # Search packages
alias nc="nh clean all --keep 5" # Keep only the 5 most recent system generations

# Bat
alias cat='bat'

# Duf 
alias df='duf'

# Dust
alias du='dust'

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
  print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
  command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
  command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
    print -P "%F{33} %F{34}Installation successful.%f%b" || \
    print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Plugins
zinit ice wait"0" lucid
zinit light aloxaf/fzf-tab
zinit ice wait"0" lucid
zinit light zsh-users/zsh-completions
zinit ice wait"0" lucid
zinit light zsh-users/zsh-autosuggestions
zinit ice wait"0" lucid
zinit light zdharma-continuum/fast-syntax-highlighting
zstyle ':fzf-tab:*' fzf-flags ${(z)FZF_DEFAULT_OPTS}

# Theme
source ~/.theme.zsh-theme

# Fastfetch
fastfetch

# Correction
setopt CORRECT

# NH
export NH_FLAKE="/etc/nixos/"

# Set up fzf key bindings and fuzzy completion
#source <(fzf --zsh)
